// Compiles boards/*.txt into lib/boards.js, the module the watch imports.
//
//   npm run pack
//
// The grids in boards/ are the source of truth: they are what a reviewer reads
// and what a diff shows. This turns them into packed codes, which are less than
// half the size and need no scanning at startup.
//
// The output is COMMITTED rather than git-ignored. A generated file in the tree
// is a small price for the guarantee that no build can ever produce a bundle
// with no boards in it - and test/boards.test.mjs re-packs the grids and
// compares, so the two cannot quietly drift apart.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { decodeCollection, packBoard } from "../lib/board-format.js";
import { LEVELS } from "../lib/levels.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const sections = [];
let total = 0;

for (const level of LEVELS) {
  const file = join(ROOT, "boards", `${level.id}.txt`);
  const collection = decodeCollection(readFileSync(file, "utf8"));

  if (collection === null) {
    console.error(`${level.id}: boards/${level.id}.txt is malformed`);
    process.exit(1);
  }
  if (collection.cols !== level.cols || collection.rows !== level.rows) {
    console.error(
      `${level.id}: boards are ${collection.cols}x${collection.rows}, ` +
        `but the difficulty is ${level.cols}x${level.rows}`
    );
    process.exit(1);
  }

  const codes = collection.boards.map((islands) => packBoard(islands));
  total += codes.length;
  sections.push(`  ${level.id}: [\n` + codes.map((code) => `    "${code}",`).join("\n") + "\n  ],");
  console.log(
    `${level.id.padEnd(7)} ${String(codes.length).padStart(5)} boards packed  ` +
      `${(codes.join("").length / 1024).toFixed(0)} KB of codes`
  );
}

const output =
  "// GENERATED by scripts/pack-boards.mjs from boards/*.txt - do not edit by hand.\n" +
  "//\n" +
  "// One packed code per board, three characters per island: column, row and the\n" +
  "// number on it, columns and rows in base 36. lib/board-format.js unpacks them.\n" +
  "// The grids in boards/ are the source of truth; run `npm run pack` after\n" +
  "// changing them.\n" +
  "export const BUILT_IN_BOARDS = {\n" +
  sections.join("\n") +
  "\n};\n";

writeFileSync(join(ROOT, "lib", "boards.js"), output, "utf8");
console.log(`wrote lib/boards.js: ${total} boards, ${(output.length / 1024).toFixed(0)} KB`);
